### ISSUE TITLE
Shift Hold

### ISSUE THREAD

**Issue by Ichisich** [RamonUnch/AltSnap#211]
Currently, if shift is pressed AFTER a window gets dragged, it toggles `Smart Aero Snapping`.
Shift pressed BEFORE or AFTER a window gets dragged, it enables `Zones` as long as the shift key is held.

These two different behaviours often contradict each other.
My recommendation would be to unify this action:
Shift disables `Smart Aero` and enables `Zones` regardless when pressed, but only as long as held.

Rationale:
`Zones` and `Smart Aero` are never needed at the same time, and there is already space for a toggle.
Shift as a non-causal hold modifier would be more intuitive.

**Comment by RamonUnch** [comment]
This build should fix it...
[AltSnap_i386.zip](https://github.com/RamonUnch/AltSnap/files/9119134/AltSnap_i386.zip)
[AltSnap_x64.zip](https://github.com/RamonUnch/AltSnap/files/9119138/AltSnap_x64.zip)

**Comment by Ichisich** [comment]
> This build should fix it... [AltSnap_i386.zip](https://github.com/RamonUnch/AltSnap/files/9119134/AltSnap_i386.zip) [AltSnap_x64.zip](https://github.com/RamonUnch/AltSnap/files/9119138/AltSnap_x64.zip)

It resolves the hold/toggle issue, but still is dependent on timing.
Pre-emptive shift hold still gets ignored when it comes to disabling smart snapping. 
(but not zones)

**Comment by RamonUnch** [comment]
You mean Shift+Hotkey+Move does not disable smarter aero snapping? For me it does like for Hotkey+Shift+Leftclick

**Comment by Ichisich** [comment]
The move part is the important one:
- Hotkey+Shift+Move doesn't disable
- Shift+Hotkey+Move doesn't disable
- Hotkey+Move+Shift does disable

**Comment by Ichisich** [comment]
I found it, it's the setting `Snap window edges to:` `+inside of windows`

The other three subsettings,
- `Disabled`
- `To screen borders`
- `+ outside of windows`

work as intended with your test build.

**Comment by RamonUnch** [comment]
Ok, then this one should fix it.
Also when `Snap window edges` is set to: `+inside of windows` then pressing shift should disable window edge snapping.
[hooks1.54test6_x64.zip](https://github.com/RamonUnch/AltSnap/files/9125682/hooks1.54test6_x64.zip)

**Comment by Ichisich** [comment]
Perfect, but on an additional note.
Your test build, not the hook.dll, interferes with the German translation, and probably other languages as well.
It seems `AdvancedMetricsBox` doesn't get recognized and as a result every subsequent entry is rearranged.

**Comment by RamonUnch** [comment]
It is a bug in AltSnap, I forgot a coma in a string list...
[AltSnap1.54test7_x64.zip](https://github.com/RamonUnch/AltSnap/files/9125830/AltSnap1.54test7_x64.zip)

**Comment by Ichisich** [comment]
Test builds gonna test.

I added:
`InputHotkeysNothing`=Nichts
`InputHotkeysAlt`=Alt
`InputHotkeysWinkey`=Windows
`InputHotkeysCtrl`=Strg
`InputHotkeysShift`=Umschalt

I guess they will be necessary with 1.54
